#include "nsIDOMEventTarget.idl"
#include "nsIDOMMozNdefRecord.idl"
#include "nsIDOMDOMRequest.idl"

[scriptable, builtinclass, uuid(c2c01a50-4779-11e1-b86c-0800200c9a66)]
interface nsIDOMNfc : nsIDOMEventTarget {

  attribute nsIDOMEventListener onndefdiscovered;
  attribute nsIDOMEventListener ontaglost;

  // records is an array of 1 or more records
  [implicit_jscontext]
  nsIDOMDOMRequest writeNdefTag(in jsval records);

  // Only for debug/development purposes to send a unfiltered
  // message to the nfcd socket
  void sendToNfcd(in DOMString message);
};
