#include "nsIDOMEventTarget.idl"
#include "nsIDOMNdefRecord.idl"
#include "nsIDOMDOMRequest.idl"

[scriptable, builtinclass, uuid(c2c01a50-4779-11e1-b86c-0800200c9a66)]
interface nsIDOMNfc : nsIDOMEventTarget {

  attribute nsIDOMEventListener onndefdiscovered;
  attribute nsIDOMEventListener ontaglost;

  // payload should be DOMString for text data and ArrayBuffer or Blob for binary data
  // See: https://developer.mozilla.org/en/DOM/XMLHttpRequest/Sending_and_Receiving_Binary_Data#Sending_binary_data
  nsIDOMDOMRequest writeNdefTag(in char tnf, in DOMString type, in DOMString id, in jsval payload);

  // Only for debug/development purposes to send a unfiltered
  // message to the nfcd socket
  void sendToNfcd(in DOMString message);
};
